#!/bin/sh

name="$USER"
browserdir="/home/$name/.librewolf"
profilesini="$browserdir/profiles.ini"

sudo -u "$name" librewolf --headless >/dev/null 2>&1 &
sleep 2
pkill -u "$name" librewolf

profile="$(sed -n "/Default=.*.default-\(default\|release\)/ s/.*=//p" "$profilesini")"
pdir="$browserdir/$profile"

installffaddons(){
	addonlist="tridactyl-vim localcdn-fork-of-decentraleyes istilldontcareaboutcookies libredirect darkreader"
	addontmp="$(mktemp -d)"
	trap "rm -fr $addontmp" HUP INT QUIT TERM PWR EXIT
	IFS=' '
	sudo -u "$name" mkdir -p "$pdir/extensions/"
	for addon in $addonlist; do
		addonurl="$(curl --silent "https://addons.mozilla.org/en-US/firefox/addon/${addon}/" | grep -o 'https://addons.mozilla.org/firefox/downloads/file/[^"]*')"
		file="${addonurl##*/}"
		sudo -u "$name" curl -LOs "$addonurl" > "$addontmp/$file"
		id="$(unzip -p "$file" manifest.json | grep "\"id\"")"
		id="${id%\"*}"
		id="${id##*\"}"
		sudo -u "$name" mv "$file" "$pdir/extensions/$id.xpi"
	done
}

[ -d "$pdir" ] && installffaddons
